platform :ios, '14.0'
use_frameworks!
source 'https://cdn.cocoapods.org/'
def sdk_dependencies
  # TODO: This needs to be a 2.1.0 internal beta
  pod 'NimbusSDK', '2.0.0', subspecs: ['NimbusKit', 'NimbusRenderVideoKit', 'NimbusRenderStaticKit', 'NimbusRequestAPSKit']
end
target 'Unity-iPhone' do
  sdk_dependencies
  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
target 'UnityFramework' do
  sdk_dependencies
end
