platform :ios, '14.0'
use_frameworks!
source 'https://cdn.cocoapods.org/'
def sdk_dependencies
  pod 'NimbusSDK', '1.11.4', subspecs: ['NimbusKit', 'NimbusRenderVideoKit', 'NimbusRenderStaticKit']
end
target 'Unity-iPhone' do
  sdk_dependencies
  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end
target 'UnityFramework' do
  sdk_dependencies
end
