name: GameCI 🎮

on: [pull_request]

jobs:
  test:
    name: Run Unit Tests 🧪
    runs-on: ubuntu-latest
    
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
          
      # Apply Pre Processor Symbols (Compiler options) 
      - name: Apply csc.rsp (pre-processor symbols)
        run: echo -define:MY_SYMBOL >> sample-app/Assets/csc.rsp

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: sample-app
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  buildPlatforms:
    name: Build for ${{ matrix.targetPlatform }}✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - sample-app
        targetPlatform:
          - Android # Build an Android player.
          - iOS # Build an iOS player.
        unityVersion:
          - 6000.0.26f1
          - auto
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      # Apply Pre Processor Symbols (Compiler options)      
      - name: Apply csc.rsp (pre-processor symbols)
        run: echo -define:MY_SYMBOL >> sample-app/Assets/csc.rsp

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
          
  