name: nimbus-unity
on:
  push:
    branches:
      - main
    paths:
      - 'com.adsbynimbus.nimbus/Runtime/Plugins/**'
      - '.github/workflows/rtbworkflow*'
  pull_request:
    paths:
      - 'com.adsbynimbus.nimbus/Runtime/Plugins/**'
      - '.github/workflows/rtbworkflow*'


jobs:
  tests:
    name: Running CSharp Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Install dependencies
        run: nuget restore
        working-directory: com.adsbynimbus.nimbus/Runtime/Plugins

      - name: Run Test
        run: dotnet test --no-restore
        working-directory: com.adsbynimbus.nimbus/Runtime/Plugins
